### ISSUE TITLE
Data input example.

### ISSUE THREAD

**Issue by jorge-h2020** [fcproj/BIGBIOCL#1]
Good morning,

I am trying to use BIGBIOCL, I see that it is all very well explained, the experiments, SupportFiles and Software. I'm trying to understand better the operation of BIGBIOCL, I get a bit confused with the explanation of the wiki and the input files, could you give me some examples of this input file?

Thanks

**Comment by fcproj** [comment]
Hi, thanks for your interest in BigBioCL.

Most of the explanation of input files used for experiments (and also examples with the expected formats of input files) is available in the paper: "Classification of large DNA methylation datasets for identifying cancer drivers" (https://www.sciencedirect.com/science/article/pii/S2214579617302708).

However, we relied on the data of The Cancer Genome Atlas (TCGA),  available at The Genomic Data Commons data sharing platform (https://gdc.nci.nih.gov/). You can reuse that dataset to validate our experiments. The publication mentioned above gives some additional details about the dataset itself and how we used it.

**Comment by hperez-ucam** [comment]
Hi, it is very likely you have some example/input files you used in this work. Could you send them to us so that we can easily and faster understand your code? Thanks a lot

**Comment by fcproj** [comment]
Unfortunately not anymore, I am sorry. But you have the official data source and the description of the entire procedure to recreate the experiment (if it's needed for the validation of the paper). Everything is well explained in the paper.
